### ISSUE TITLE
Unable to update base64Key file for base64Key while backing up to nextcloud

### ISSUE THREAD

**Issue by jnnkB** [stevesoltys/backup#335]
I'm currently unable to complete a backup to my local nextcloud. It did complete yesterday but since then it always fails at around 12-13 percent. Using `adb logcat` I got the following messages around the time I get the 'Backup failed' notification:

```log
10-28 11:48:58.485  8407  8427 E KVBackup: Unable to update base64Key file for base64Key bm90aWZpY2F0aW9uczpub3RpZmljYXRpb25z
10-28 11:48:58.485  8407  8427 E KVBackup: java.io.FileNotFoundException: Failed to open document for writing bm90aWZpY2F0aW9uczpub3RpZmljYXRpb25z
10-28 11:48:58.485  8407  8427 E KVBackup: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:704)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1816)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1518)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.getOutputStream(DocumentsStorage.kt:164)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at com.stevesoltys.seedvault.plugins.saf.DocumentsProviderKVBackup.getOutputStreamForRecord(DocumentsProviderKVBackup.kt:66)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at com.stevesoltys.seedvault.transport.backup.KVBackup.storeRecord(KVBackup.kt:165)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at com.stevesoltys.seedvault.transport.backup.KVBackup.storeRecords(KVBackup.kt:135)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at com.stevesoltys.seedvault.transport.backup.KVBackup.performBackup(KVBackup.kt:109)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at com.stevesoltys.seedvault.transport.backup.KVBackup$performBackup$1.invokeSuspend(Unknown Source:13)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.ResumeModeKt.resumeUninterceptedMode(ResumeMode.kt:45)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.TimeoutCoroutine.afterCompletionInternal(Timeout.kt:100)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:310)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.JobSupport.tryFinalizeFinishingState(JobSupport.kt:236)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:849)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:811)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:787)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:111)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.performBackup(ConfigurableBackupTransport.kt:147)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at android.app.backup.BackupTransport$TransportImpl.performBackup(BackupTransport.java:704)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:626)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at android.os.Binder.execTransactInternal(Binder.java:1154)
10-28 11:48:58.485  8407  8427 E KVBackup: 	at android.os.Binder.execTransact(Binder.java:1123)
10-28 11:48:58.485  8407  8427 I KVBackup: Resetting state because of K/V Backup error of android
10-28 11:48:58.487  8407  8643 I NotificationBackupObserver: Completed. Target: android, status: -1000
10-28 11:48:58.487  8407  8643 I NotificationBackupObserver: Showing progress notification for @pm@ 1/212
10-28 11:48:58.487  8407  8643 I BackupNotificationManager: 32/242 - 13% - Android System
10-28 11:48:58.492  7721 11071 V UploadsStorageManager: getUploads() got 100 rows from page 5, 600 rows total so far, last ID 735
10-28 11:48:58.492  7721 11071 D UploadsStorageManager: QUERY: _id < ? ROWID: 735
10-28 11:48:58.493  8407  8427 I BackupCoordinator: Request incremental backup time. Returned 0
10-28 11:48:58.494  1506 22107 I KeyValueBackupTask: K/V backup pass finished
10-28 11:48:58.497  8407  8643 I NotificationBackupObserver: Backup finished 2/212. Status: -1000
10-28 11:48:58.497  8407  8407 D ConfigurableBackupTransportService: Service destroyed.
10-28 11:48:58.497  1506 22107 V BackupManagerService: [UserID:0] Released wakelock:*backup*-0-3333
10-28 11:48:58.502  7721 11071 V UploadsStorageManager: getUploads() got 100 rows from page 6, 700 rows total so far, last ID 635
10-28 11:48:58.502  7721 11071 D UploadsStorageManager: QUERY: _id < ? ROWID: 635
10-28 11:48:58.510  7721 11071 V UploadsStorageManager: getUploads() got 100 rows from page 7, 800 rows total so far, last ID 535
10-28 11:48:58.510  7721 11071 D UploadsStorageManager: QUERY: _id < ? ROWID: 535
10-28 11:48:58.518  7721 11071 V UploadsStorageManager: getUploads() got 100 rows from page 8, 900 rows total so far, last ID 435
10-28 11:48:58.518  7721 11071 D UploadsStorageManager: QUERY: _id < ? ROWID: 435
10-28 11:48:58.525  7721 11071 V UploadsStorageManager: getUploads() got 100 rows from page 9, 1000 rows total so far, last ID 335
10-28 11:48:58.525  7721 11071 D UploadsStorageManager: QUERY: _id < ? ROWID: 335
10-28 11:48:58.532  7721 11071 V UploadsStorageManager: getUploads() got 100 rows from page 10, 1100 rows total so far, last ID 235
10-28 11:48:58.532  7721 11071 D UploadsStorageManager: QUERY: _id < ? ROWID: 235
10-28 11:48:58.539  7721 11071 V UploadsStorageManager: getUploads() got 100 rows from page 11, 1200 rows total so far, last ID 135
10-28 11:48:58.539  7721 11071 D UploadsStorageManager: QUERY: _id < ? ROWID: 135
10-28 11:48:58.546  7721 11071 V UploadsStorageManager: getUploads() got 100 rows from page 12, 1300 rows total so far, last ID 35
10-28 11:48:58.546  7721 11071 D UploadsStorageManager: QUERY: _id < ? ROWID: 35
10-28 11:48:58.551  7721 11071 V UploadsStorageManager: getUploads() got 34 rows from page 13, 1334 rows total so far, last ID 1
10-28 11:48:58.551  7721 11071 D UploadsStorageManager: QUERY: _id < ? ROWID: 1
10-28 11:48:58.554  7721 11071 V UploadsStorageManager: getUploads() got 0 rows from page 14, 1334 rows total so far, last ID 1
10-28 11:48:58.554  7721 11071 V UploadsStorageManager: getUploads() returning 1334 (1334) rows after reading 15 pages
10-28 11:48:58.554  7721 11071 V UploadsStorageManager: Updating /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/admin@dietpi.fritz.box%2Fnextcloud/.SeedVaultAndroidBackup/1635372032087/kv/android/YWNjb3VudF9zeW5jX3NldHRpbmdzOmFjY291bnRfZGF0YQ with status=UPLOAD_IN_PROGRESS
10-28 11:48:58.563  7721 11071 D UploadsStorageManager: updateUpload returns with: 1 for file: /storage/emulated/0/Android/media/com.nextcloud.client/nextcloud/admin@dietpi.fritz.box%2Fnextcloud/.SeedVaultAndroidBackup/1635372032087/kv/android/YWNjb3VudF9zeW5jX3NldHRpbmdzOmFjY291bnRfZGF0YQ
```

**Comment by grote** [comment]
`Failed to open document for writing` nothing we can do about it. Nextcloud is very flaky.

**Comment by grote** [comment]
@rugk let's move the Nextcloud specific part of your bug report here and leave the other one for the storage backups bugs.

**Comment by rugk** [comment]
Wait what? I'm sorry but I don't know what exactly is Nextcloud-specific etc. So feel free to comment/post whatever you want here.

**Comment by grote** [comment]
What is here looks like an issue when uploading to Nextcloud, nothing in Seedvault itself.
