### ISSUE TITLE
ConfigurableBackupTransport not registered

### ISSUE THREAD

**Issue by Rudd-O** [stevesoltys/backup#351]
https://gist.github.com/Rudd-O/b9220fe765c6ccc8dfac9c9c89c65659

OS: latest GOS, Pixel 4 XL.

```
12-30 19:42:53.554  1506  2055 E BackupManagerService: [UserID:0] Unable to get configuration intent from transport: Transport com.stevesoltys.seedvault.transport.ConfigurableBackupTransport not registered
12-30 19:42:53.554  1506  2055 E BackupManagerService: [UserID:0] Unable to get destination string from transport: Transport com.stevesoltys.seedvault.transport.ConfigurableBackupTransport not registered
12-30 19:42:53.554  1506  7059 E BackupManagerService: [UserID:0] Unable to get management intent from transport: Transport com.stevesoltys.seedvault.transport.ConfigurableBackupTransport not registered
12-30 19:42:53.555  1506  2055 E BackupManagerService: [UserID:0] Unable to get management label from transport: Transport com.stevesoltys.seedvault.transport.ConfigurableBackupTransport not registered
```

As a result, the backup settings screen appears totally empty.

**Comment by Rudd-O** [comment]
```
12-30 19:42:53.512  1506  2055 E BackupManagerService: [UserID:0] Unable to get management intent from transport: Transport com.stevesoltys.seedvault.transport.ConfigurableBackupTransport not registered
12-30 19:42:53.512  4397  4397 E BackupSettingsHelper: Backup transport has not provided an intent or the component for the intent is not found!
```

**Comment by grote** [comment]
The upstream ticket has more info. Looks like the app is crashing because it can't read metadata from the cache:

```
E 16:16:24.849 3857 3857 E AndroidRuntime: Process: com.stevesoltys.seedvault, PID: 3857 02-23 16:16:24.849 3857 3857
E AndroidRuntime: java.lang.AssertionError: Error reading metadata from cache 02-23 16:16:24.849 3857 3857
E AndroidRuntime: at com.stevesoltys.seedvault.metadata.MetadataManager.getMetadata(MetadataManager.kt:43) 02-23 16:16:24.849 3857 3857 E AndroidRuntime: at com.stevesoltys.seedvault.metadata.MetadataManager.getBackupToken(MetadataManager.kt:195) 02-23 16:16:24.849 3857 3857
E AndroidRuntime: at com.stevesoltys.seedvault.App.migrateTokenFromMetadataToSettingsManager(App.kt:102) 02-23 16:16:24.849 3857 3857 E AndroidRuntime: at com.stevesoltys.seedvault.App.access$migrateTokenFromMetadataToSettingsManager(App.kt:37) 02-23 16:16:24.849 3857 3857
E AndroidRuntime: at com.stevesoltys.seedvault.App$onCreate$2.invoke(App.kt:87) 02-23 16:16:24.849 3857 3857
E AndroidRuntime: at com.stevesoltys.seedvault.App$onCreate$2.invoke(App.kt:37) 02-23 16:16:24.849 3857 3857
E AndroidRuntime: at com.stevesoltys.seedvault.AppKt.permitDiskReads(App.kt:131) 02-23 16:16:24.849 3857 3857
E AndroidRuntime: at com.stevesoltys.seedvault.App.onCreate(App.kt:86) 02-23 
```

Probably a duplicate of #213. 

@Rudd-O how's your storage situation? Did your internal storage ever run full?

**Comment by grote** [comment]
@Rudd-O now I see that  there's two people commenting in that downstream ticket. Your logcat doesn't actually to show the reason why the transport is not registered. We would need more logs to find out why. It may or may not be the same issue.

**Comment by Rudd-O** [comment]
@grote yes my storage ran full at one point in time, but since has been erased.

I cannot furnish the logs anymore.  I wiped the phone clean after migrating to the new phone (which is the exact reason why I needed the backup to work).

**Comment by Rudd-O** [comment]
Looks to me like the bug I experienced is the same as #213.  Should pursue it further.
