### ISSUE TITLE
CalyxOS: Backup Manager is not activated for user 0

### ISSUE THREAD

**Issue by 1fexd** [stevesoltys/backup#400]
Hi,

i'm trying to use Seedvault 12-3.0 on CalyxOS 3.4.0 on a Pixel 3 and when I toggle "Backup my apps" nothing happens. If I click "Backup status" and go back, the toggle resets. "Backup now" via the kebab menu on the top right doesn't do anything.

**Comment by grote** [comment]
> when I toggle "Backup my apps" nothing happens. If I click "Backup status" and go back, the toggle resets.

This sounds like the backup manager from the OS is not getting activated as it should.

Is this an official CalyxOS or something self-built?

**Comment by 1fexd** [comment]
Official calyx

**Comment by grote** [comment]
Can you run `adb shell bmgr list transports` and post the results?

**Comment by 1fexd** [comment]
`Error: Backup Manager is not activated for user 0`

I just google the error message and this came up: https://github.com/seedvault-app/seedvault/issues/77
I am using Shelter aswell, so I think this issue is a duplicate; A detailed error message in seedvault would be nice instead of just silently failing

`adb shell bmgr --user 0 activate true` fails with

```    
Exception caught:
java.lang.SecurityException: No permission to configure backup activity
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
	at android.os.Parcel.createException(Parcel.java:2409)
	at android.os.Parcel.readException(Parcel.java:2392)
	at android.os.Parcel.readException(Parcel.java:2334)
	at android.app.backup.IBackupManager$Stub$Proxy.setBackupServiceActive(IBackupManager.java:3460)
	at com.android.commands.bmgr.Bmgr.doActivateService(Bmgr.java:898)
	at com.android.commands.bmgr.Bmgr.run(Bmgr.java:115)
	at com.android.commands.bmgr.Bmgr.main(Bmgr.java:90)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.backup.BackupManagerService.enforcePermissionsOnUser(BackupManagerService.java:425)
	at com.android.server.backup.BackupManagerService.setBackupServiceActive(BackupManagerService.java:442)
	at android.app.backup.IBackupManager$Stub.onTransact(IBackupManager.java:1693)
	at android.os.Binder.execTransactInternal(Binder.java:1179)
	at android.os.Binder.execTransact(Binder.java:1143)
```

**Comment by chirayudesai** [comment]
Are you opening Seedvault in the main user or the Shelter created work profile?

**Comment by 1fexd** [comment]
Main user

**Comment by 1fexd** [comment]
Hi, have there been any further developments?

Kind regards

**Comment by grote** [comment]
Calyx has built-in work-profile feature. Maybe using Shelter has messed things up here. 

No idea why the backup manager would be disabled for main user. More of a Calyx than a Seedvault issue I'd say.

**Comment by 1fexd** [comment]
@chirayudesai this issue is still occuring on CalyxOS 4.2.7 Android 13 on a Pixel 5. I am not using Shelter but the built-in work profile manager
