### ISSUE TITLE
cloud backups hang at 27%

### ISSUE THREAD

**Issue by ItamiWasTaken** [stevesoltys/backup#424]
when using davx5s WebDAV and when using Nextcloud.
there's no issue for local backups (on device and USB).

please tell me if more info is needed

**Comment by ItamiWasTaken** [comment]
possible bug with seedvault or davx5?

**Comment by grote** [comment]
We would need logcat from short before the hang happens until some time after the hang to find out what is happening in your case.

Also, does it *always* hang at that percentage? I just did a DavX5 backup and already got to 29% myself.

**Comment by ItamiWasTaken** [comment]
once I get to my laptop, I'll figure out how to get a logcat and comment it here

**Comment by ItamiWasTaken** [comment]
I do apologize in advance if it's not filtered the best, it's my first time running a logcat
the bits near the very end seem promising though

[logcat.txt](https://github.com/seedvault-app/seedvault/files/9080106/logcat.txt)

**Comment by ItamiWasTaken** [comment]
> We would need logcat from short before the hang happens until some time after the hang to find out what is happening in your case.
> 
> Also, does it _always_ hang at that percentage? I just did a DavX5 backup and already got to 29% myself.

Seems it's hanging at 26% rather than 27%, so thats consistant. the logcat was run when I ran the backup, and it stopped outputing anything once seedvault failed
see the txt file attached to my previous comment

**Comment by grote** [comment]
Strange thing, there seem to be cut error logs. Various of these:

```ruby
07-10 19:42:18.648 10454 10963 E BackupCoordinator: 	at com.stevesoltys.seedvault.transport.backup.ApkBackupKt.copyStreamsAndGetHash(ApkBackup.kt:225)
07-10 19:42:18.648 10454 10963 E BackupCoordinator: 	at com.stevesoltys.seedvault.transport.backup.ApkBackup.backupApkIfNecessary(ApkBackup.kt:108)
07-10 19:42:18.648 10454 10963 E BackupCoordinator: 	at com.stevesoltys.seedvault.transport.backup.ApkBackup$backupApkIfNecessary$1.invokeSuspend(Unknown Source:15)
07-10 19:42:18.648 10454 10963 E BackupCoordinator: 	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.getBackupQuota(ConfigurableBackupTransport.kt:125)
```

Different variant:

```ruby
07-10 19:44:35.426 14124 14137 E BackupCoordinator: 	at com.stevesoltys.seedvault.transport.backup.ApkBackupKt.copyStreamsAndGetHash(ApkBackup.kt:225)
07-10 19:44:35.426 14124 14137 E BackupCoordinator: 	at com.stevesoltys.seedvault.transport.backup.ApkBackup.backupApkIfNecessary(ApkBackup.kt:108)
07-10 19:44:35.426 14124 14137 E BackupCoordinator: 	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.backUpApk(BackupCoordinator.kt:455)
07-10 19:44:35.426 14124 14137 E BackupCoordinator: 	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.backUpApksOfNotBackedUpPackages$packages__apps__Seedvault__android_common__Seedvault(BackupCoordinator.kt:423)
07-10 19:44:35.426 14124 14137 E BackupCoordinator: 	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.finishBackup(BackupCoordinator.kt:384)
07-10 19:44:35.426 14124 14137 E BackupCoordinator: 	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator$finishBackup$1.invokeSuspend(Unknown Source:14)
07-10 19:44:35.426 14124 14137 E BackupCoordinator: 	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.finishBackup(ConfigurableBackupTransport.kt:133)
```

Another one:

```ruby
07-10 19:51:31.247 14761 14845 E FullBackup: 	at com.stevesoltys.seedvault.transport.backup.FullBackup.sendBackupData(FullBackup.kt:166)
07-10 19:51:31.247 14761 14845 E FullBackup: 	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.sendBackupData(BackupCoordinator.kt:291)
07-10 19:51:31.247 14761 14845 E FullBackup: 	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$sendBackupData$1.invokeSuspend(ConfigurableBackupTransport.kt:190)
07-10 19:51:31.247 14761 14845 E FullBackup: 	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.sendBackupData(ConfigurableBackupTransport.kt:189)
```

@ItamiWasTaken did you apply some custom filtering or something to the log or is this the raw output that was captured?

**Comment by grote** [comment]
No idea what this is about and why something would want to restart seedvault:

@ItamiWasTaken what ROM and seedvault version is this?

```ruby
07-10 19:55:53.126  7069  7069 D AppButtonsPrefCtl: Sending broadcast to query restart status for com.stevesoltys.seedvault
07-10 19:55:53.222  7069  7069 D AppButtonsPrefCtl: Got broadcast response: Restart status for com.stevesoltys.seedvault true
07-10 19:55:53.249  2275  4478 I Role    : com.stevesoltys.seedvault not qualified for android.app.role.HOME due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.intent.action.MAIN', mCategories='[android.intent.category.HOME]', mDataScheme='null', mDataType='null'}, mPermission='null'}
07-10 19:55:53.251  2275  4478 I Role    : com.stevesoltys.seedvault not qualified for android.app.role.DIALER due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.intent.action.DIAL', mCategories='[]', mDataScheme='null', mDataType='null'}, mPermission='null'}
07-10 19:55:53.251  2275  4478 I Role    : com.stevesoltys.seedvault not qualified for android.app.role.EMERGENCY due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.telephony.action.EMERGENCY_ASSISTANCE', mCategories='[]', mDataScheme='null', mDataType='null'}, mPermission='null'}
07-10 19:55:53.253  2275  4478 I Role    : com.stevesoltys.seedvault not qualified for android.app.role.SMS due to missing RequiredComponent{mIntentFilterData=IntentFilterData{mAction='android.provider.Telephony.SMS_DELIVER', mCategories='[]', mDataScheme='null', mDataType='null'}, mPermission='android.permission.BROADCAST_SMS'}
```

**Comment by ItamiWasTaken** [comment]
to answer your first question@grote, I don't think I added any filters

I'm using CalyxOS version 3.7.0
Seedvault version 12-3.0

**Comment by ItamiWasTaken** [comment]
I changed to another nextcloud instance and it seems to be working as intended now. I checked the nextcloud instance I was using it I couldn't access the domain so seems that could've been the issue
