### ISSUE TITLE
Backup with Nexcloud makes Nexcloud to crash and backup hangs forever. 

### ISSUE THREAD

**Issue by christophehenry** [stevesoltys/backup#440]
Everything is in the title. Everytime Seedvault starts a backup, I get a pop-up saying Nexcloud keep crashing and the Seedvault on going backup notification stays there and doesn't progress.

I have noticed this behavior for a couple of days days. Before that, Seedvault was able to backup, but seemingly not Nexcloud (always marking "awaiting backup…").

Maybe related to a Nexcloud update?

I'll join the NC stacktrace later when I can debug.

**Edit** here is the promised stacktrace:

```com.nextcloud.client   E  FATAL EXCEPTION: main
    Process: com.nextcloud.client, PID: 12423
    android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.nextcloud.client/com.owncloud.android.files.services.FileUploader
      at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
      at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
      at android.os.Parcel.readParcelable(Parcel.java:3334)
      at android.os.Parcel.createExceptionOrNull(Parcel.java:2421)
      at android.os.Parcel.createException(Parcel.java:2410)
      at android.os.Parcel.readException(Parcel.java:2393)
      at android.os.Parcel.readException(Parcel.java:2335)
      at android.app.IActivityManager$Stub$Proxy.startService(IActivityManager.java:6033)
      at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1856)
      at android.app.ContextImpl.startForegroundService(ContextImpl.java:1832)
      at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:781)
      at com.owncloud.android.files.services.FileUploader.uploadUpdateFile(FileUploader.java:1034)
      at com.owncloud.android.files.services.FileUploader.uploadUpdateFile(FileUploader.java:1010)
      at com.owncloud.android.providers.DocumentsStorageProvider.lambda$openDocument$3(DocumentsStorageProvider.java:264)
      at com.owncloud.android.providers.DocumentsStorageProvider$$ExternalSyntheticLambda0.onClose(Unknown Source:11)
      at android.os.ParcelFileDescriptor$1.onFileDescriptorEvents(ParcelFileDescriptor.java:321)
      at android.os.MessageQueue.dispatchEvents(MessageQueue.java:293)
      at android.os.MessageQueue.nativePollOnce(Native Method)
      at android.os.MessageQueue.next(MessageQueue.java:335)
      at android.os.Looper.loopOnce(Looper.java:161)
      at android.os.Looper.loop(Looper.java:288)
      at android.app.ActivityThread.main(ActivityThread.java:7870)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
```

This may be related to battery optimisation. As soon as I started the NC app myself and deactivated battery optmisation for it, the problem was solved. I had several application not working correctly on LineageOS since version 19.1 because of bettery optimisation, e.g Element or Fedilab not receiving broadcast events from ntfy (UnifiedPush) or HTTP request launched by `WorkManager` constantly failing…

So maybe not directly related to Seedvault.

**Comment by grote** [comment]
Relevenat parts of the log:

```
    android.app.ForegroundServiceStartNotAllowedException: startForegroundService() not allowed due to mAllowStartForeground false: service com.nextcloud.client/com.owncloud.android.files.services.FileUploader
      at com.owncloud.android.files.services.FileUploader.uploadUpdateFile(FileUploader.java:1034)
```

Looks like a Nextcloud bug to me. Nothing we can do about it.
