### ISSUE TITLE
Crash after connecting USB storage and performing automatic backup

### ISSUE THREAD

**Issue by PatrykMis** [stevesoltys/backup#443]
GrapheneOS

```
type: crash
osVersion: google/flame/flame:13/TP1A.220905.004/2022090600:user/release-keys
package: com.stevesoltys.seedvault:30000231
process: com.stevesoltys.seedvault

java.lang.AssertionError: Have state for @pm@
	at com.stevesoltys.seedvault.transport.backup.KVBackup.performBackup(KVBackup.kt:85)
	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.performIncrementalBackup(BackupCoordinator.kt:249)
	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$performBackup$1.invokeSuspend(ConfigurableBackupTransport.kt:150)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.performBackup(ConfigurableBackupTransport.kt:149)
	at android.app.backup.BackupTransport$TransportImpl.performBackup(BackupTransport.java:754)
	at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:652)
	at android.os.Binder.execTransactInternal(Binder.java:1307)
	at android.os.Binder.execTransact(Binder.java:1265)

```

**Comment by grote** [comment]
If your seedvault version starts with `11`, please see https://github.com/seedvault-app/seedvault/issues/438#issuecomment-1231642677

**Comment by grote** [comment]
Closing, since version code seems to be `30000231`. It might still be interesting to see more logs here than just the stack trace to understand how this situation could happen. seedvault and `system_server` would be interesting.
