### ISSUE TITLE
Error initializing local backup location

### ISSUE THREAD

**Issue by InfiniteLukeOne** [stevesoltys/backup#448]
I have a problem with using Seedvault.

When I select the local device in the backup location, the device shows "Preparing storage location... Error accessing storage location." (Translated by me)

`adb logcat` shows this error:
```
09-15 19:51:57.781 17367 17507 E JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)                                                      
09-15 19:51:57.781 17367 17507 E JavaBinder: java.security.UnrecoverableKeyException: Key algorithm unknown                                                                            
09-15 19:51:57.781 17367 17507 E JavaBinder:    at android.security.keystore2.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:387)             
09-15 19:51:57.781 17367 17507 E JavaBinder:    at android.security.keystore2.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyFromKeystore(AndroidKeyStoreProvider.java:339)             
09-15 19:51:57.781 17367 17507 E JavaBinder:    at android.security.keystore2.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:110)                                             
09-15 19:51:57.781 17367 17507 E JavaBinder:    at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:482)                                                                      
09-15 19:51:57.781 17367 17507 E JavaBinder:    at java.security.KeyStore.getEntry(KeyStore.java:1560)                                                                                 
09-15 19:51:57.781 17367 17507 E JavaBinder:    at com.stevesoltys.seedvault.crypto.KeyManagerImpl.getMainKey(KeyManager.kt:93)                                                        
09-15 19:51:57.781 17367 17507 E JavaBinder:    at com.stevesoltys.seedvault.crypto.CryptoImpl$key$2.invoke(Crypto.kt:126)                                                             
09-15 19:51:57.781 17367 17507 E JavaBinder:    at com.stevesoltys.seedvault.crypto.CryptoImpl$key$2.invoke(Crypto.kt:125)                                                             
09-15 19:51:57.781 17367 17507 E JavaBinder:    at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)                                                                                 
09-15 19:51:57.781 17367 17507 E JavaBinder:    at com.stevesoltys.seedvault.crypto.CryptoImpl.getKey(Crypto.kt:125)                                                                   
09-15 19:51:57.781 17367 17507 E JavaBinder:    at com.stevesoltys.seedvault.crypto.CryptoImpl.newEncryptingStream(Crypto.kt:157)                                                      
09-15 19:51:57.781 17367 17507 E JavaBinder:    at com.stevesoltys.seedvault.metadata.MetadataWriterImpl.write(MetadataWriter.kt:23)                                                   
09-15 19:51:57.781 17367 17507 E JavaBinder:    at com.stevesoltys.seedvault.metadata.MetadataManager.modifyMetadata(MetadataManager.kt:188)                                           
09-15 19:51:57.781 17367 17507 E JavaBinder:    at com.stevesoltys.seedvault.metadata.MetadataManager.onDeviceInitialization(MetadataManager.kt:65)                                    
09-15 19:51:57.781 17367 17507 E JavaBinder:    at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.initializeDevice(BackupCoordinator.kt:127)                             
09-15 19:51:57.781 17367 17507 E JavaBinder:    at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$initializeDevice$1.invokeSuspend(ConfigurableBackupTransport.kt:115)
09-15 19:51:57.781 17367 17507 E JavaBinder:    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)                                              
09-15 19:51:57.781 17367 17507 E JavaBinder:    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)                                                                            
09-15 19:51:57.781 17367 17507 E JavaBinder:    at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)                                                      
09-15 19:51:57.781 17367 17507 E JavaBinder:    at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)                                                                   
09-15 19:51:57.781 17367 17507 E JavaBinder:    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)                                                               
09-15 19:51:57.781 17367 17507 E JavaBinder:    at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)                                                                         
09-15 19:51:57.781 17367 17507 E JavaBinder:    at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)                                                       
09-15 19:51:57.781 17367 17507 E JavaBinder:    at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)                                                                 
09-15 19:51:57.781 17367 17507 E JavaBinder:    at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.initializeDevice(ConfigurableBackupTransport.kt:114)                
09-15 19:51:57.781 17367 17507 E JavaBinder:    at android.app.backup.BackupTransport$TransportImpl.initializeDevice(BackupTransport.java:698)                                         
09-15 19:51:57.781 17367 17507 E JavaBinder:    at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:603)                                             
09-15 19:51:57.781 17367 17507 E JavaBinder:    at android.os.Binder.execTransactInternal(Binder.java:1184)                                                                            
09-15 19:51:57.781 17367 17507 E JavaBinder:    at android.os.Binder.execTransact(Binder.java:1143)                                                                                    
09-15 19:51:57.786  4724  7977 E BackupManagerService: Unexpected error performing init                                                                                                
09-15 19:51:57.786  4724  7977 E BackupManagerService: java.lang.IllegalStateException: Unexpected state in finishBackup()                                                             
09-15 19:51:57.786  4724  7977 E BackupManagerService:  at android.os.Parcel.createExceptionOrNull(Parcel.java:2434)                                                                   
09-15 19:51:57.786  4724  7977 E BackupManagerService:  at android.os.Parcel.createException(Parcel.java:2410)                                                                         
09-15 19:51:57.786  4724  7977 E BackupManagerService:  at android.os.Parcel.readException(Parcel.java:2393)                                                                           
09-15 19:51:57.786  4724  7977 E BackupManagerService:  at android.os.Parcel.readException(Parcel.java:2335)                                                                           
09-15 19:51:57.786  4724  7977 E BackupManagerService:  at com.android.internal.backup.IBackupTransport$Stub$Proxy.finishBackup(IBackupTransport.java:1247)                            
09-15 19:51:57.786  4724  7977 E BackupManagerService:  at com.android.server.backup.internal.PerformInitializeTask.run(PerformInitializeTask.java:136)                                
09-15 19:51:57.786  4724  7977 E BackupManagerService:  at android.os.Handler.handleCallback(Handler.java:938)                                                                         
09-15 19:51:57.786  4724  7977 E BackupManagerService:  at android.os.Handler.dispatchMessage(Handler.java:99)                                                                         
09-15 19:51:57.786  4724  7977 E BackupManagerService:  at com.android.server.backup.internal.BackupHandler.dispatchMessageInternal(BackupHandler.java:130)                            
09-15 19:51:57.786  4724  7977 E BackupManagerService:  at com.android.server.backup.internal.BackupHandler.dispatchMessage(BackupHandler.java:118)                                    
09-15 19:51:57.786  4724  7977 E BackupManagerService:  at android.os.Looper.loopOnce(Looper.java:201)                                                                                 
09-15 19:51:57.786  4724  7977 E BackupManagerService:  at android.os.Looper.loop(Looper.java:288)                                                                                     
09-15 19:51:57.786  4724  7977 E BackupManagerService:  at android.os.HandlerThread.run(HandlerThread.java:67)              
```

Environment:
- Galaxy S8 (SM-G950F)
- LineageOS 19.1 (Android 12)
- Seedvault Version 12-3.0 (was installed with the OS)

Can you help me?

**Comment by grote** [comment]
`UnrecoverableKeyException: Key algorithm unknown` sounds very strange like your device doesn't support this kind of key. @mikeNG is that possible? The phone seems old, but Android 12.

**Comment by mikeNG** [comment]
This sounds like keystore is not properly working on this custom ROM (similar to another issue that I can't remember the bug ID at the moment). This device does not receive official LineageOS builds so we can't guarantee it passes the device requirements charter, which includes full basic functionality

**Comment by grote** [comment]
Thanks @mikeNG! So not our issue.
