### ISSUE TITLE
Backup to nextcloud fails with Primary directory nextcloud not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]

### ISSUE THREAD

**Issue by reactormonk** [stevesoltys/backup#450]
The backup fails at initialization, didn't tell it to backup anything just yet. Lineage build RQ3A.2110011.011, FP3.

<details><summary>logs</summary>

```
          MediaProvider  W  Forgot to handle a top level directory in getContentUriForFile?
                         E  insertFileIfNecessary failed
                         E  java.lang.IllegalArgumentException: Primary directory nextcloud not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
                         E      at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:2744)
                         E      at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:2409)
                         E      at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:3062)
                         E      at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3614)
                         E      at com.android.providers.media.MediaProvider.insert(MediaProvider.java:3330)
                         E      at com.android.providers.media.MediaProvider.insertFileForFuse(MediaProvider.java:6800)
                         E      at com.android.providers.media.MediaProvider.insertFileIfNecessaryForFuse(MediaProvider.java:6887)
          DatabaseUtils  E  Writing exception to parcel
                         E  android.os.ParcelableException: java.io.FileNotFoundException: File could not be created
                         E      at android.provider.DocumentsProvider.call(DocumentsProvider.java:1080)
                         E      at android.content.ContentProvider.call(ContentProvider.java:2448)
                         E      at android.content.ContentProvider$Transport.call(ContentProvider.java:517)
                         E      at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:295)
                         E      at android.os.Binder.execTransactInternal(Binder.java:1154)
                         E      at android.os.Binder.execTransact(Binder.java:1123)
                         E  Caused by: java.io.FileNotFoundException: File could not be created
                         E      at com.owncloud.android.providers.DocumentsStorageProvider.getFileNotFoundExceptionWithCause(DocumentsStorageProvider.java:677)
                         E      at com.owncloud.android.providers.DocumentsStorageProvider.createFile(DocumentsStorageProvider.java:547)
                         E      at com.owncloud.android.providers.DocumentsStorageProvider.createDocument(DocumentsStorageProvider.java:486)
                         E      at android.provider.DocumentsProvider.callUnchecked(DocumentsProvider.java:1142)
                         E      at android.provider.DocumentsProvider.call(DocumentsProvider.java:1078)
                         E      ... 5 more
                         E  Caused by: java.io.IOException: Operation not permitted
                         E      at java.io.UnixFileSystem.createFileExclusively0(Native Method)
                         E      at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
                         E      at java.io.File.createNewFile(File.java:1008)
                         E      at com.owncloud.android.providers.DocumentsStorageProvider.createFile(DocumentsStorageProvider.java:543)
                         E      ... 8 more
      DocumentsContract  W  Failed to create document
                         W  android.os.ParcelableException: java.io.FileNotFoundException: File could not be created
                         W      at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
                         W      at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
                         W      at android.os.Parcel.readParcelable(Parcel.java:3281)
                         W      at android.os.Parcel.createExceptionOrNull(Parcel.java:2368)
                         W      at android.os.Parcel.createException(Parcel.java:2357)
                         W      at android.os.Parcel.readException(Parcel.java:2340)
                         W      at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
                         W      at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
                         W      at android.content.ContentProviderProxy.call(ContentProviderNative.java:732)
                         W      at android.content.ContentResolver.call(ContentResolver.java:2405)
                         W      at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1371)
                         W      at androidx.documentfile.provider.TreeDocumentFile.createFile(TreeDocumentFile.java:54)
                         W      at androidx.documentfile.provider.TreeDocumentFile.createFile(TreeDocumentFile.java:45)
                         W      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorageKt.createOrGetFile(DocumentsStorage.kt:181)
                         W      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorageKt.createOrGetFile$default(DocumentsStorage.kt:178)
                         W      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage$rootBackupDir$1.invokeSuspend(DocumentsStorage.kt:60)
                         W      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         W      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
                         W      at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
                         W      at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
                         W      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
                         W      at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                         W      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
                         W      at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                         W      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.getRootBackupDir$packages__apps__Seedvault__android_common__Seedvault(DocumentsStorage.kt:52)
                         W      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage$currentSetDir$1.invokeSuspend(DocumentsStorage.kt:81)
                         W      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         W      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
                         W      at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
                         W      at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
                         W      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
                         W      at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                         W      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
                         W      at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                         W      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.getCurrentSetDir(DocumentsStorage.kt:77)
                         W      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.access$getCurrentSetDir$p(DocumentsStorage.kt:38)
                         W      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage$currentFullBackupDir$1.invokeSuspend(DocumentsStorage.kt:94)
                         W      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         W      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
                         W      at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
                         W      at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
                         W      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
                         W      at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                         W      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
                         W      at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                         W      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.getCurrentFullBackupDir(DocumentsStorage.kt:91)
                         W      at com.stevesoltys.seedvault.plugins.saf.DocumentsProviderFullBackup.getOutputStream(DocumentsProviderFullBackup.kt:23)
                         W      at com.stevesoltys.seedvault.transport.backup.FullBackup$performFullBackup$2.invokeSuspend(FullBackup.kt:113)
                         W      at com.stevesoltys.seedvault.transport.backup.FullBackup$performFullBackup$2.invoke(Unknown Source:10)
                         W      at com.stevesoltys.seedvault.transport.backup.FullBackup$sendBackupData$outputStream$1.invokeSuspend(FullBackup.kt:156)
                         W      at com.stevesoltys.seedvault.transport.backup.FullBackup$sendBackupData$outputStream$1.invoke(Unknown Source:10)
                         W      at com.stevesoltys.seedvault.transport.backup.FullBackup.sendBackupData(FullBackup.kt:155)
                         W      at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.sendBackupData(BackupCoordinator.kt:304)
                         W      at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$sendBackupData$1.invokeSuspend(ConfigurableBackupTransport.kt:188)
                         W      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         W      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
                         W      at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
                         W      at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
                         W      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
                         W      at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                         W      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
                         W      at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                         W      at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.sendBackupData(ConfigurableBackupTransport.kt:187)
                         W      at android.app.backup.BackupTransport$TransportImpl.sendBackupData(BackupTransport.java:765)
                         W      at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:765)
                         W      at android.os.Binder.execTransactInternal(Binder.java:1159)
                         W      at android.os.Binder.execTransact(Binder.java:1123)
                         W  Caused by: java.io.FileNotFoundException: File could not be created
                         W      at java.lang.reflect.Constructor.newInstance0(Native Method)
                         W      at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                         W      at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
                         W      ... 67 more
       DocumentsStorage  E  Error creating root backup dir.
                         E  java.io.IOException
                         E      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorageKt.createOrGetFile(DocumentsStorage.kt:185)
                         E      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorageKt.createOrGetFile$default(DocumentsStorage.kt:178)
                         E      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage$rootBackupDir$1.invokeSuspend(DocumentsStorage.kt:60)
                         E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         E      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
                         E      at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
                         E      at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
                         E      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
                         E      at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                         E      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
                         E      at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                         E      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.getRootBackupDir$packages__apps__Seedvault__android_common__Seedvault(DocumentsStorage.kt:52)
                         E      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage$currentSetDir$1.invokeSuspend(DocumentsStorage.kt:81)
                         E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         E      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
                         E      at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
                         E      at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
                         E      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
                         E      at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                         E      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
                         E      at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                         E      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.getCurrentSetDir(DocumentsStorage.kt:77)
                         E      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.access$getCurrentSetDir$p(DocumentsStorage.kt:38)
                         E      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage$currentFullBackupDir$1.invokeSuspend(DocumentsStorage.kt:94)
                         E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         E      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
                         E      at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
                         E      at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
                         E      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
                         E      at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                         E      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
                         E      at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                         E      at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.getCurrentFullBackupDir(DocumentsStorage.kt:91)
                         E      at com.stevesoltys.seedvault.plugins.saf.DocumentsProviderFullBackup.getOutputStream(DocumentsProviderFullBackup.kt:23)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup$performFullBackup$2.invokeSuspend(FullBackup.kt:113)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup$performFullBackup$2.invoke(Unknown Source:10)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup$sendBackupData$outputStream$1.invokeSuspend(FullBackup.kt:156)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup$sendBackupData$outputStream$1.invoke(Unknown Source:10)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup.sendBackupData(FullBackup.kt:155)
                         E      at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.sendBackupData(BackupCoordinator.kt:304)
                         E      at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$sendBackupData$1.invokeSuspend(ConfigurableBackupTransport.kt:188)
                         E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         E      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
                         E      at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
                         E      at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
                         E      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
                         E      at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                         E      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
                         E      at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                         E      at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.sendBackupData(ConfigurableBackupTransport.kt:187)
                         E      at android.app.backup.BackupTransport$TransportImpl.sendBackupData(BackupTransport.java:765)
                         E      at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:765)
                         E      at android.os.Binder.execTransactInternal(Binder.java:1159)
                         E      at android.os.Binder.execTransact(Binder.java:1123)
             FullBackup  E  Error getting OutputStream for full backup of de.eos.uptrade.android.fahrinfo.berlin
                         E  java.io.IOException
                         E      at com.stevesoltys.seedvault.plugins.saf.DocumentsProviderFullBackup.getOutputStream(DocumentsProviderFullBackup.kt:24)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup$performFullBackup$2.invokeSuspend(FullBackup.kt:113)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup$performFullBackup$2.invoke(Unknown Source:10)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup$sendBackupData$outputStream$1.invokeSuspend(FullBackup.kt:156)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup$sendBackupData$outputStream$1.invoke(Unknown Source:10)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup.sendBackupData(FullBackup.kt:155)
                         E      at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.sendBackupData(BackupCoordinator.kt:304)
                         E      at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$sendBackupData$1.invokeSuspend(ConfigurableBackupTransport.kt:188)
                         E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         E      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
                         E      at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
                         E      at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
                         E      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
                         E      at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                         E      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
                         E      at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                         E      at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.sendBackupData(ConfigurableBackupTransport.kt:187)
                         E      at android.app.backup.BackupTransport$TransportImpl.sendBackupData(BackupTransport.java:765)
                         E      at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:765)
                         E      at android.os.Binder.execTransactInternal(Binder.java:1159)
                         E      at android.os.Binder.execTransact(Binder.java:1123)
                         E  Error handling backup data for de.eos.uptrade.android.fahrinfo.berlin:
                         E  java.io.IOException
                         E      at com.stevesoltys.seedvault.plugins.saf.DocumentsProviderFullBackup.getOutputStream(DocumentsProviderFullBackup.kt:24)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup$performFullBackup$2.invokeSuspend(FullBackup.kt:113)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup$performFullBackup$2.invoke(Unknown Source:10)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup$sendBackupData$outputStream$1.invokeSuspend(FullBackup.kt:156)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup$sendBackupData$outputStream$1.invoke(Unknown Source:10)
                         E      at com.stevesoltys.seedvault.transport.backup.FullBackup.sendBackupData(FullBackup.kt:155)
                         E      at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.sendBackupData(BackupCoordinator.kt:304)
                         E      at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$sendBackupData$1.invokeSuspend(ConfigurableBackupTransport.kt:188)
                         E      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                         E      at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
                         E      at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:270)
                         E      at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
                         E      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
                         E      at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
                         E      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
                         E      at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
                         E      at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.sendBackupData(ConfigurableBackupTransport.kt:187)
                         E      at android.app.backup.BackupTransport$TransportImpl.sendBackupData(BackupTransport.java:765)
                         E      at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:765)
                         E      at android.os.Binder.execTransactInternal(Binder.java:1159)
                         E      at android.os.Binder.execTransact(Binder.java:1123)
```

</details>

**Comment by grote** [comment]
Looks like there's something wrong with Nextcloud. It isn't allowed to create the file for some reason. Looks like an upstream issue.

**Comment by reactormonk** [comment]
Yup, was upstream issue.
