### ISSUE TITLE
Backup Error (Failed resolution of: Landroidx/fragment/app/FragmentViewModelLazyKt)

### ISSUE THREAD

**Issue by alabotski** [stevesoltys/backup#456]
I have Xiaomi MiPad 4
And install LineageOS 20 (Android 13)
https://forum.xda-developers.com/t/lineageos-20-0-android-13-for-mi-pad-4-plus.4501317/#post-87525275

Turn on backup in Google Disk (not system app)
And now have error

![Screenshot_20221009-213544_Nova Launcher](https://user-images.githubusercontent.com/439337/194864417-c4d0ca19-40cf-4dcb-86af-ba908b9ad900.png)

What could be the reason?

Logs
[logcat_10-09-2022_21-45-53.txt](https://github.com/seedvault-app/seedvault/files/9745834/logcat_10-09-2022_21-45-53.txt)
[crash-com-stevesoltys-seedvault-09-10_21-45-40.zip](https://github.com/seedvault-app/seedvault/files/9745841/crash-com-stevesoltys-seedvault-09-10_21-45-40.zip)

**Comment by chirayudesai** [comment]
That looks like a bad build of the app in your ROM.

What's the Seedvault version -> you can check it inside the app (menu on top right then about), or through Settings

**Comment by alabotski** [comment]
@chirayudesai 
I can't run seedvault it crashes

With SD Maid app
I see - com.stevesoltys.seedvault 13-3.1 (33000301)

**Comment by grote** [comment]
Relevant stacktrace:

```ruby
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/fragment/app/FragmentViewModelLazyKt;
	at com.stevesoltys.seedvault.settings.SettingsFragment.<init>(SettingsFragment.kt:278)
	at com.stevesoltys.seedvault.settings.SettingsActivity.onCreate(SettingsActivity.kt:34)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8269)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.ClassNotFoundException: androidx.fragment.app.FragmentViewModelLazyKt
	... 18 more
```

**Comment by mikeNG** [comment]
Should be fixed with https://review.lineageos.org/c/LineageOS/android_packages_apps_Seedvault/+/341601
