### ISSUE TITLE
Hanging backup status notification

### ISSUE THREAD

**Issue by grote** [stevesoltys/backup#471]
The background backup status notification for app backups just stays forever, never getting dismissed.

Unfortunately, there are no logs from seedvault or DavX5 here:

```ruby
11-15 15:46:45.540  1000  2237  2237 I backup_transport_connection: [com.stevesoltys.seedvault/.transport.ConfigurableBackupTransportService,1]
11-15 15:46:45.546  1000  2237 32590 I backup_start: com.stevesoltys.seedvault.transport.ConfigurableBackupTransport
11-15 15:46:45.540  1000  2237  2237 I TransportConnection: ConfigurableBackupTransportService#187: Notifying [BH/MSG_RUN_BACKUP] transport = BackupTransportClient
11-15 15:46:45.541  1000  2237  4178 V BackupManagerService: Running a backup pass
11-15 15:46:45.542  1000  2237  4178 V BackupManagerService: [UserID:0] Acquired wakelock:*backup*-0-4178
11-15 15:46:45.542  1000  2237  4178 V BackupManagerService: clearing pending backups
11-15 15:46:45.545  1000  2237  4178 D KeyValueBackupTask: Spinning thread key-value-backup-5
11-15 15:46:45.545  1000  2237 32590 D PFTBT   : backupmanager pftbt token=92d1122
11-15 15:46:45.545  1000  2237 32590 V KeyValueBackupTask: Beginning backup of 6 targets
11-15 15:46:45.548  1000  2237 32590 D KeyValueBackupTask: Starting key-value backup of @pm@
11-15 15:46:45.557  1000  2237 32590 D KeyValueBackupTask: Invoking agent on @pm@
...
11-15 15:46:46.312  1000  2237  2404 I PowerManagerService: Dozing...
...
11-15 15:48:19.895  1017   699   699 I keystore2: keystore2::super_key: In try_unlock_user_with_biometric: Successfully unlocked with biometric
11-15 15:48:19.896  1017   699   699 I keystore2: keystore2::authorization: on_lock_screen_event(LockScreenEvent(0), user_id=10, password.is_some()=false, unlocking_sids=Some([6455556990593732120]))
11-15 15:48:19.906  1017   699   699 W keystore2: keystore2::super_key: In try_unlock_user_with_biometric: attempt failed: In use_key_in_one_step: Failed to begin operation.
11-15 15:48:19.906  1017   699   699 W keystore2:
11-15 15:48:19.906  1017   699   699 W keystore2: Caused by:
11-15 15:48:19.906  1017   699   699 W keystore2:     0: In upgrade_keyblob_if_required_with: Closure failed
11-15 15:48:19.906  1017   699   699 W keystore2:     1: Error::Km(ErrorCode(-26))
...
11-15 15:51:45.614  1000  2237 32590 I backup_transport_failure: @pm@
...
11-15 15:51:45.613  1000  2237 32590 W TransportStatusCallback: Couldn't get operation status from transport
11-15 15:51:45.615  1000  2237 32590 E KeyValueBackupTask: Error during PM metadata backup
11-15 15:51:45.615  1000  2237 32590 E KeyValueBackupTask: com.android.server.backup.keyvalue.TaskException
11-15 15:51:45.615  1000  2237 32590 E KeyValueBackupTask:      at com.android.server.backup.keyvalue.KeyValueBackupTask.handleTransportStatus(KeyValueBackupTask.java:1135)
11-15 15:51:45.615  1000  2237 32590 E KeyValueBackupTask:      at com.android.server.backup.keyvalue.KeyValueBackupTask.sendDataToTransport(KeyValueBackupTask.java:1069)
11-15 15:51:45.615  1000  2237 32590 E KeyValueBackupTask:      at com.android.server.backup.keyvalue.KeyValueBackupTask.sendDataToTransport(KeyValueBackupTask.java:576)
11-15 15:51:45.615  1000  2237 32590 E KeyValueBackupTask:      at com.android.server.backup.keyvalue.KeyValueBackupTask.backupPm(KeyValueBackupTask.java:681)
11-15 15:51:45.615  1000  2237 32590 E KeyValueBackupTask:      at com.android.server.backup.keyvalue.KeyValueBackupTask.run(KeyValueBackupTask.java:367)
11-15 15:51:45.615  1000  2237 32590 E KeyValueBackupTask:      at java.lang.Thread.run(Thread.java:1012)
```

```ruby
11-15 16:01:45.626  1000  2237 32590 W BackupTransportClient: Failed to get result from transport:
11-15 16:01:45.626  1000  2237 32590 W BackupTransportClient: java.util.concurrent.TimeoutException
11-15 16:01:45.626  1000  2237 32590 W BackupTransportClient:   at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1862)
11-15 16:01:45.626  1000  2237 32590 W BackupTransportClient:   at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1997)
11-15 16:01:45.626  1000  2237 32590 W BackupTransportClient:   at com.android.server.backup.transport.BackupTransportClient.getFutureResult(BackupTransportClient.java:377)
11-15 16:01:45.626  1000  2237 32590 W BackupTransportClient:   at com.android.server.backup.transport.BackupTransportClient.requestBackupTime(BackupTransportClient.java:159)
11-15 16:01:45.626  1000  2237 32590 W BackupTransportClient:   at com.android.server.backup.keyvalue.KeyValueBackupTask.revertTask(KeyValueBackupTask.java:1239)
11-15 16:01:45.626  1000  2237 32590 W BackupTransportClient:   at com.android.server.backup.keyvalue.KeyValueBackupTask.run(KeyValueBackupTask.java:387)
11-15 16:01:45.626  1000  2237 32590 W BackupTransportClient:   at java.lang.Thread.run(Thread.java:1012)
11-15 16:01:45.638  1000  2237 32590 I KeyValueBackupTask: K/V backup pass finished
11-15 16:01:45.644  1000  2237 32590 V BackupManagerService: [UserID:0] Released wakelock:*backup*-0-4178
```

**Comment by chirayudesai** [comment]
> 11-15 15:46:46.312  1000  2237  2404 I PowerManagerService: Dozing...

Could be a hint

https://developer.android.com/training/monitoring-device-state/doze-standby

**Comment by grote** [comment]
Looks like we have returned an unknown status for some reason? Maybe we crashed?

```java
        // Any other error here indicates a transport-level failure.
```

https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/backup/java/com/android/server/backup/keyvalue/KeyValueBackupTask.java;l=1135;drc=b45a2ea782074944f79fc388df20b06e01f265f7

Edit: Ah no, could also just have been `TRANSPORT_ERROR`. However, why did we not remove out notification?

**Comment by grote** [comment]
Since we are getting `TimeoutException` in `KeyValueBackupTask#revertTask()`, it might be that the `KeyValueBackupTask` is never informing our `NotificationBackupObserver` about the finished backup which could be seen as an upstream bug.

**Comment by ernstlustig** [comment]
Lineage 19.1 on an ASUS Zenfone 8 via WebDAV to my NextCloud: stuck at 73%. After a while it says Backup failed. Most apps show a yellow triangle (not backed up as it wasn't used recently), some have a green check.
Next try: same behaviour.
