### ISSUE TITLE
Backup fail on GrapheneOS with 13-3.3

### ISSUE THREAD

**Issue by nazar-pc** [stevesoltys/backup#513]
GrapheneOS recently imported latest version of Seedvault and I can't do backups with it (not that it really worked before either), it just errors after two seconds since I initiate it.

In particular I saw this error:

<details>

```
02-09 01:39:49.704  4847  4874 V KVBackup:   Delta operation key app.grapheneos.apps   size 44
02-09 01:39:49.706  4847  4874 I KVBackup: Finish K/V Backup of @pm@ - needs upload: true
02-09 01:39:50.167  4847  4874 E KVBackup: Error uploading DB
02-09 01:39:50.167  4847  4874 E KVBackup: java.io.FileNotFoundException: Failed to open document for writing KLwFJpRF0f-xAmXAN-9KAI1HfwU4IA5L4Jk-5S8tJrE
02-09 01:39:50.167  4847  4874 E KVBackup: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:705)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1880)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1582)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.getOutputStream(DocumentsStorage.kt:142)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at com.stevesoltys.seedvault.plugins.saf.DocumentsProviderStoragePlugin.getOutputStream(DocumentsProviderStoragePlugin.kt:66)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at com.stevesoltys.seedvault.transport.backup.KVBackup.uploadDb(KVBackup.kt:244)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at com.stevesoltys.seedvault.transport.backup.KVBackup.finishBackup(KVBackup.kt:208)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.finishBackup(BackupCoordinator.kt:371)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$finishBackup$1.invokeSuspend(ConfigurableBackupTransport.kt:134)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.finishBackup(ConfigurableBackupTransport.kt:133)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at android.app.backup.BackupTransport$TransportImpl.finishBackup(BackupTransport.java:775)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:670)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at android.os.Binder.execTransactInternal(Binder.java:1307)
02-09 01:39:50.167  4847  4874 E KVBackup: 	at android.os.Binder.execTransact(Binder.java:1265)
02-09 01:39:50.168  4847  4874 I NotificationBackupObserver: Completed. Target: @pm@, status: -1000
02-09 01:39:50.168  4847  4874 I NotificationBackupObserver: Showing progress notification for null 0/143
02-09 01:39:50.168  1386  5141 E KeyValueBackupTask: Error during PM metadata backup
02-09 01:39:50.168  1386  5141 E KeyValueBackupTask: com.android.server.backup.keyvalue.TaskException
02-09 01:39:50.168  1386  5141 E KeyValueBackupTask: 	at com.android.server.backup.keyvalue.KeyValueBackupTask.handleTransportStatus(KeyValueBackupTask.java:1135)
02-09 01:39:50.168  1386  5141 E KeyValueBackupTask: 	at com.android.server.backup.keyvalue.KeyValueBackupTask.sendDataToTransport(KeyValueBackupTask.java:1069)
02-09 01:39:50.168  1386  5141 E KeyValueBackupTask: 	at com.android.server.backup.keyvalue.KeyValueBackupTask.sendDataToTransport(KeyValueBackupTask.java:576)
02-09 01:39:50.168  1386  5141 E KeyValueBackupTask: 	at com.android.server.backup.keyvalue.KeyValueBackupTask.backupPm(KeyValueBackupTask.java:681)
02-09 01:39:50.168  1386  5141 E KeyValueBackupTask: 	at com.android.server.backup.keyvalue.KeyValueBackupTask.run(KeyValueBackupTask.java:367)
02-09 01:39:50.168  1386  5141 E KeyValueBackupTask: 	at java.lang.Thread.run(Thread.java:1012)
02-09 01:39:50.168  4847  4874 I BackupNotificationManager: 27/169 - 16% - Менеджер системних пакетів
02-09 01:39:50.170  4847  5028 I BackupCoordinator: Request incremental backup time. Returned 0
02-09 01:39:50.172  1386  5141 I KeyValueBackupTask: K/V backup pass finished
02-09 01:39:50.173  4847  4847 W BackupNotificationManager: Needed to clean up notification with ID 1
02-09 01:39:50.173  4847  4847 D ConfigurableBackupTransportService: Service destroyed.
02-09 01:39:50.173  1386  5141 V BackupManagerService: [UserID:0] Released wakelock:*backup*-0-4499
02-09 01:39:50.174  4847  5028 I NotificationBackupObserver: Backup finished 1/143. Status: -1000
02-09 01:39:50.378  1386  1386 I NotificationService: Cannot find enqueued record for key: 0|com.stevesoltys.seedvault|1|null|10036
```

</details>

Let me know if there are any other details I can provide that can help to get to the bottom of this.

**Comment by grote** [comment]
Thanks for the logcat. That's really helpful. It says `Failed to open document for writing`, so there's an issue with the storage you use to store the backup on. Did you try another storage?

**Comment by nazar-pc** [comment]
I only wanted to use Nextcloud for this. Application (Nextcloud) seems to work, I also don't see any upload errors related to this process in Nextcloud either.

I just tried the device's own storage and it did work. What else do I debug from here?

**Comment by grote** [comment]
You'd need to debug the nextcloud app, or like me, switch to using DavX5 to connect to Nextcloud instead.

**Comment by nazar-pc** [comment]
Yep, DavX5 worked just like local. Every time I try to use Nextcloud Android app for something, it either doesn't support or work or doesn't work the way I expect it to.

I have not seen anything error-like about Nextcloud in logs, so I guess I'll just get rid of it again and use DavX5 going forward.

BTW, I don't think DavX5 was supported in version 11 of Seedvault, so I'm glad this upgrade was finally done in GrapheneOS.

Feel free to close this issue if there is nothing else I can help with here.
