### ISSUE TITLE
Unable to backup: generated directories are empty, "backup now" option in burger menu greyed out

### ISSUE THREAD

**Issue by christophehenry** [stevesoltys/backup#516]
I'm using LineageOS which embeds Seedvault by default. I haven't been able to backup for a few weeks now. Symptoms are: 
- the "backup now" in burger menu is greyed out,
- backup status indicates "never" (after I reset the app to try to correct the problem)
- all apps show the warning flag on the "backup status page"
- generated folders on storage are all empty.
- no error appeared in the log during the backup.

As I haven't been able to backup for a few weeks now, I tried to fix the problem today by:
- turn off the "Backup my apps option",
- remove the `.SeedVaultAndroidBackup` on storage,
- reset the recovery code,
- turn on the "Backup my apps option".

Then I keep having the symptoms described earlier.

**Comment by chirayudesai** [comment]
Which device and LineageOS build is this with?

Edit: Also, what's the SeedVault version?

**Comment by christophehenry** [comment]
I'm on a OnePlus 5T running Lineage 20-20230215-microg-dumpling (LineageOS for microG) with SeedVault 13-3.3.

**Comment by grote** [comment]
Can you choose the internal storage location and if that fails, please export logs via expert settings?

**Comment by christophehenry** [comment]
SeedVault seems to backup correctly on internal storage. But when going back to Nextcloud storage I find a bunch of errors like this in the logs:

```
Backed up new APK of *****.*****.***** with version ******.
Error while writing APK or metadata for *****.*****.*****
java.io.FileNotFoundException: Failed to open document for writing .backup.metadata
	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
	at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:705)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1860)
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1562)
	at com.stevesoltys.seedvault.plugins.saf.DocumentsStorage.getOutputStream(DocumentsStorage.kt:142)
	at com.stevesoltys.seedvault.plugins.saf.DocumentsProviderStoragePlugin.getOutputStream(DocumentsProviderStoragePlugin.kt:66)
	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.getMetadataOutputStream(BackupCoordinator.kt:511)
	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.getMetadataOutputStream$default(BackupCoordinator.kt:509)
	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.backUpApk(BackupCoordinator.kt:466)
	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.backUpApksOfNotBackedUpPackages$packages__apps__Seedvault__android_common__Seedvault(BackupCoordinator.kt:430)
	at com.stevesoltys.seedvault.transport.backup.BackupCoordinator.finishBackup(BackupCoordinator.kt:386)
	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$finishBackup$1.invokeSuspend(ConfigurableBackupTransport.kt:134)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.finishBackup(ConfigurableBackupTransport.kt:133)
	at android.app.backup.BackupTransport$TransportImpl.finishBackup(BackupTransport.java:775)
	at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:670)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1244)
02-27 17:02:18.881 32183 32282 I BackupCoordinator: Package *****.*****.***** was in null, update to NOT_ALLOWED
Error backing up opt-out APK of *****.*****.*****
```

Seems to be an access issue?

**Comment by grote** [comment]
Thanks! That internal storage works is a good sign. Can you try Davx5 app for backup to your nextcloud server instead of the Nextcloud app?

**Comment by christophehenry** [comment]
Yep, backup completes without error using DavX5  storage.

**Comment by grote** [comment]
great, so maybe use this app going forward. In my experience it is much more reliable than the nextcloud app.
