### ISSUE TITLE
Seedvault not backing up and "keeps stopping"

### ISSUE THREAD

**Issue by ghost** [stevesoltys/backup#575]
Seedvault version: 13-3.3
Running GrapheneOS on a Google Pixel 6

https://github.com/seedvault-app/seedvault/assets/127934267/51123d18-a209-46de-9c7d-080bcc2b0b69

Android 13 Crash Report:

type: crash
osVersion: google/oriole/oriole:13/TQ3A.230901.001/2023100300:user/release-keys
package: com.stevesoltys.seedvault:33030030
process: com.stevesoltys.seedvault
processUptime: 12028 + 213 ms

```kotlin
java.lang.IllegalStateException: No storage set
	at com.stevesoltys.seedvault.storage.SeedvaultStoragePlugin.getRoot(SeedvaultStoragePlugin.kt:24)
	at org.calyxos.backup.storage.plugin.saf.SafStoragePlugin.getFolder(SafStoragePlugin.kt:56)
	at org.calyxos.backup.storage.plugin.saf.SafStoragePlugin.getCurrentBackupSnapshots$suspendImpl(SafStoragePlugin.kt:239)
	at org.calyxos.backup.storage.plugin.saf.SafStoragePlugin.getCurrentBackupSnapshots(Unknown Source:0)
	at org.calyxos.backup.storage.api.StorageBackup$deleteAllSnapshots$2.invokeSuspend(StorageBackup.kt:116)
	at org.calyxos.backup.storage.api.StorageBackup$deleteAllSnapshots$2.invoke(Unknown Source:8)
	at org.calyxos.backup.storage.api.StorageBackup$deleteAllSnapshots$2.invoke(Unknown Source:4)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at org.calyxos.backup.storage.api.StorageBackup.deleteAllSnapshots(StorageBackup.kt:114)
	at com.stevesoltys.seedvault.ui.storage.BackupStorageViewModel$onLocationSet$1.invokeSuspend(BackupStorageViewModel.kt:38)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@6ae63e, Dispatchers.IO]

```

**Comment by grote** [comment]
Thanks for the report with a stacktrace.

This may be related to #556 and/or #557. Can you try re-selecting the USB drive in "Backup location"? If that produces the same error, can you copy files to that drive via the Files app?

**Comment by arodier** [comment]
Exactly same bug here. I am using LineageOS 20.

**Comment by grote** [comment]
op is a ghost and the backup location process has been refactored since, so I hope this is solved, if not please create a new ticket.
