### ISSUE TITLE
Backup service crashes on startup in Android Pie

### ISSUE THREAD

**Issue by stevesoltys** [stevesoltys/backup#6]
This actually causes the operating system to become unusable, since when the service crashes, user is prompted to enter their password again.

```
11-11 15:06:59.742  4547  5576 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: backup
11-11 15:06:59.742  4547  5576 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.stevesoltys.backup.transport.component.BackupComponent.currentDestinationString()' on a null object reference
11-11 15:06:59.742  4547  5576 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:1948)
11-11 15:06:59.742  4547  5576 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1910)
11-11 15:06:59.742  4547  5576 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1860)
11-11 15:06:59.742  4547  5576 E AndroidRuntime:        at com.android.internal.backup.IBackupTransport$Stub$Proxy.currentDestinationString(IBackupTransport.java:434)
11-11 15:06:59.742  4547  5576 E AndroidRuntime:        at com.android.server.backup.TransportManager.registerTransport(TransportManager.java:638)
11-11 15:06:59.742  4547  5576 E AndroidRuntime:        at com.android.server.backup.TransportManager.registerTransport(TransportManager.java:614)
11-11 15:06:59.742  4547  5576 E AndroidRuntime:        at com.android.server.backup.TransportManager.registerTransportsForIntent(TransportManager.java:550)
11-11 15:06:59.742  4547  5576 E AndroidRuntime:        at com.android.server.backup.TransportManager.registerTransports(TransportManager.java:520)
11-11 15:06:59.742  4547  5576 E AndroidRuntime:        at com.android.server.backup.-$$Lambda$pM_c5tVAGDtxjxLF_ONtACWWq6Q.run(Unknown Source:2)
11-11 15:06:59.742  4547  5576 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
11-11 15:06:59.742  4547  5576 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
11-11 15:06:59.742  4547  5576 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
11-11 15:06:59.742  4547  5576 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by stevesoltys** [comment]
Resolved via 9f3d01e4f90a056e0174a21f6f99a896e001da00.
