### ISSUE TITLE
Hide non-updated system apps from install screen

### ISSUE THREAD

**Issue by t-m-w** [stevesoltys/backup#654]
The Restore process shows many system apps which "failed" to be installed, but there is no actual problem; they simply should not be shown.

<img src="https://github.com/seedvault-app/seedvault/assets/7275539/cfe6d17a-1813-4152-b3cc-5ef81ace2e2b" width="240" />

Affected system apps in CalyxOS, all showing "Tap to install":
- System package manager
- User Dictionary
- Settings
- Android Keyboard (AOSP)
- Quickstep
- Nfc Service
- System Tracing
- com.android.health.connect.backuprestore
- Files
- Work Setup
- Blocked Numbers Storage
- System package manager (hmm, listed twice maybe?)
- RemoteProvisioner
- com.android.wallpaperbackup
- CalyxOS App Installer
- Camera
- com.android.providers.partnerbookmarks
- Call Log Backup/Restore
- System UI
- Settings Storage
- com.android.cellbroadcastreceiver
- microG Services
- Wireless emergency alerts
- com.android.ondevicepersonalization.services.OnDevicePersonalizationApplication
- Android System

**Comment by grote** [comment]
@t-m-w do you remember if this is resolved now with the latest changes (e.g. https://github.com/seedvault-app/seedvault/pull/670)?

**Comment by t-m-w** [comment]
Sorry, I don't recall (and didn't yesterday either, just forgot to say so then).

**Comment by grote** [comment]
I think this should be solved. Please re-open if not.

**Comment by t-m-w** [comment]
Reopening for now, but if you think this is representative of a different issue, I can move this to another one / new one.

I tried a restore with the latest changes, and now, there are only five system app failures:
- Call Log Backup/Restore
- Blocked Numbers Storage
- User Dictionary
- System UI
- System Tracing

That's obviously a lot fewer than before. There is also no "Some apps not installed" popup either; just this:
<img width="240" src="https://github.com/user-attachments/assets/e46383b2-e0fc-422e-8409-e68cd3b47272"/>

Here's the error for one of them. The others' errors are the same.

<details open><summary>Logcat snippet</summary>

```
08-15 16:47:06.675 10172  4675  4690 I RestoreCoordinator: Next restore package!
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator: Error finding restore data for com.android.providers.userdictionary.
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator: java.io.IOException: No data found for com.android.providers.userdictionary. Skipping.
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at com.stevesoltys.seedvault.transport.restore.RestoreCoordinator.nextRestorePackage(RestoreCoordinator.kt:252)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport$nextRestorePackage$1.invokeSuspend(ConfigurableBackupTransport.kt:231)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at com.stevesoltys.seedvault.transport.ConfigurableBackupTransport.nextRestorePackage(ConfigurableBackupTransport.kt:230)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at android.app.backup.BackupTransport$TransportImpl.nextRestorePackage(BackupTransport.java:834)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at com.android.internal.backup.IBackupTransport$Stub.onTransact(IBackupTransport.java:718)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at android.os.Binder.execTransactInternal(Binder.java:1505)
08-15 16:47:06.734 10172  4675  4690 E RestoreCoordinator:      at android.os.Binder.execTransact(Binder.java:1444)
```
</details>

Note that the restore set may not have had the very latest Seedvault changes at the time of creation, but the latest the CalyxOS had available as of within the last month or two.

**Comment by grote** [comment]
It sounds to me like the original issue was about installing apps while the latest comment is about restoring data. It seems like a different issue and up for discussion if we should hide errors (like no data) for system app data restore.
