### ISSUE TITLE
WebDAV error: IOException: unexpected end of stream

### ISSUE THREAD

**Issue by grote** [stevesoltys/backup#675]
```ruby
06-02 20:46:51.996 14068 14106 E KVBackup: Error uploading DB
06-02 20:46:51.996 14068 14106 E KVBackup: java.io.IOException: Pipe closed
06-02 20:46:51.996 14068 14106 E KVBackup: 	at java.io.PipedInputStream.read(PipedInputStream.java:312)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at java.io.PipedInputStream.read(PipedInputStream.java:384)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at java.io.InputStream.read(InputStream.java:218)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:106)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at com.stevesoltys.seedvault.plugins.webdav.WebDavStorage$getOutputStream$body$1.writeTo(WebDavStorage.kt:80)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:62)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at at.bitfire.dav4jvm.BasicDigestAuthHandler.intercept(BasicDigestAuthHandler.kt:291)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at at.bitfire.dav4jvm.DavResource$put$1.invoke(DavResource.kt:406)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at at.bitfire.dav4jvm.DavResource$put$1.invoke(DavResource.kt:391)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at at.bitfire.dav4jvm.DavResource.followRedirects$build(DavResource.kt:607)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at at.bitfire.dav4jvm.DavResource.put(DavResource.kt:391)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at at.bitfire.dav4jvm.DavResource.put$default(DavResource.kt:390)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at com.stevesoltys.seedvault.plugins.webdav.WebDavStorage$getOutputStream$deferred$1.invokeSuspend(WebDavStorage.kt:86)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
06-02 20:46:51.996 14068 14106 E KVBackup: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
06-02 20:46:51.996 14068 14106 E KVBackup: 	Suppressed: java.io.IOException: unexpected end of stream on https://foo.bar.com/...
06-02 20:46:51.996 14068 14106 E KVBackup: 		at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:210)
06-02 20:46:51.996 14068 14106 E KVBackup: 		at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
06-02 20:46:51.996 14068 14106 E KVBackup: 		at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
06-02 20:46:51.996 14068 14106 E KVBackup: 		... 27 more
06-02 20:46:51.996 14068 14106 E KVBackup: 	Caused by: java.io.EOFException: \n not found: limit=0 content=…
06-02 20:46:51.996 14068 14106 E KVBackup: 		at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:335)
06-02 20:46:51.996 14068 14106 E KVBackup: 		at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
06-02 20:46:51.996 14068 14106 E KVBackup: 		at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
06-02 20:46:51.996 14068 14106 E KVBackup: 		... 29 more
```

**Comment by grote** [comment]
the main issue here is that this happened to all key/value backups, even `@pm@` which then caused the entire backup to fail and the system to do a re-init of the entire backup storage, so we created a new restore set duplicating all data.

**Comment by grote** [comment]
Still happening sometimes with smaller chunks with 5.0 

```ruby
10-23 17:37:49.275 16116 16763 E FullBackup: Error handling backup data for org.fdroid.basic.debug: 
10-23 17:37:49.275 16116 16763 E FullBackup: java.io.IOException: unexpected end of stream on https://example.com/...
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:210)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at at.bitfire.dav4jvm.BasicDigestAuthHandler.intercept(BasicDigestAuthHandler.kt:303)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at at.bitfire.dav4jvm.DavResource.put$lambda$18(DavResource.kt:465)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at at.bitfire.dav4jvm.DavResource.$r8$lambda$Vf0bD867Wnl2_qIkb4GLmFtj5hE(Unknown Source:0)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at at.bitfire.dav4jvm.DavResource$$ExternalSyntheticLambda5.invoke(D8$$SyntheticClass:0)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at at.bitfire.dav4jvm.DavResource.followRedirects$build(DavResource.kt:666)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at at.bitfire.dav4jvm.DavResource.put(DavResource.kt:450)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at at.bitfire.dav4jvm.DavResource.put$default(DavResource.kt:448)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at org.calyxos.seedvault.core.backends.webdav.WebDavBackend$save$deferred$1.invokeSuspend(WebDavBackend.kt:144)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
10-23 17:37:49.275 16116 16763 E FullBackup: Caused by: java.io.EOFException: \n not found: limit=0 content=…
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:335)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
10-23 17:37:49.275 16116 16763 E FullBackup: 	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
10-23 17:37:49.275 16116 16763 E FullBackup: 	... 30 more
```

**Comment by grote** [comment]
Also happens at 5.0 when pruning. Here it is interesting that a `SocketTimeoutException` is involved:

```ruby
11-04 21:09:38.876 19466 19485 I c.s.s.r.Pruner: [DefaultDispatcher-worker-1] Removing blob bar
11-04 21:09:38.877 19466 19485 D o.c.s.c.b.w.WebDavBackend: [DefaultDispatcher-worker-1] remove(Blob(repoId=foo, name=bar))
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: [DefaultDispatcher-worker-1] Error while pruning: java.net.SocketTimeoutException: failed to connect to example.com (port 443) from foo (port 44770) after 30000ms
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at libcore.io.IoBridge.connect(IoBridge.java:179)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at java.net.Socket.connect(Socket.java:646)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at at.bitfire.dav4jvm.DavResource.delete$lambda$20(DavResource.kt:498)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at at.bitfire.dav4jvm.DavResource.$r8$lambda$zT5csj47DyO5wJWpogtHNE6zRa0(Unknown Source:0)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at at.bitfire.dav4jvm.DavResource$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at at.bitfire.dav4jvm.DavResource.followRedirects$build(DavResource.kt:666)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at at.bitfire.dav4jvm.DavResource.delete(DavResource.kt:489)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at at.bitfire.dav4jvm.DavResource.delete$default(DavResource.kt:487)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at org.calyxos.seedvault.core.backends.webdav.WebDavBackend.remove(WebDavBackend.kt:312)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at com.stevesoltys.seedvault.repo.Pruner.pruneUnusedBlobs(Pruner.kt:83)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at com.stevesoltys.seedvault.repo.Pruner.removeOldSnapshotsAndPruneUnusedBlobs(Pruner.kt:67)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at com.stevesoltys.seedvault.worker.AppBackupPruneWorker.doWork(AppBackupPruneWorker.kt:59)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at com.stevesoltys.seedvault.worker.AppBackupPruneWorker$doWork$1.invokeSuspend(Unknown Source:14)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	Suppressed: java.io.IOException: unexpected end of stream on https://example.com/...
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 		at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:210)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 		at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 		at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
11-04 21:10:13.951 19466 19485 E c.s.s.w.AppBackupPruneWorker: 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-04 21:10:13.952 19466 19485 E c.s.s.w.AppBackupPruneWorker: 		at at.bitfire.dav4jvm.BasicDigestAuthHandler.intercept(BasicDigestAuthHandler.kt:303)
11-04 21:10:13.952 19466 19485 E c.s.s.w.AppBackupPruneWorker: 		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
11-04 21:10:13.952 19466 19485 E c.s.s.w.AppBackupPruneWorker: 		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
11-04 21:10:13.952 19466 19485 E c.s.s.w.AppBackupPruneWorker: 		... 26 common frames omitted
11-04 21:10:13.952 19466 19485 E c.s.s.w.AppBackupPruneWorker: 	Caused by: java.io.EOFException: \n not found: limit=0 content=…
11-04 21:10:13.952 19466 19485 E c.s.s.w.AppBackupPruneWorker: 		at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:335)
11-04 21:10:13.952 19466 19485 E c.s.s.w.AppBackupPruneWorker: 		at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
11-04 21:10:13.952 19466 19485 E c.s.s.w.AppBackupPruneWorker: 		at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
11-04 21:10:13.952 19466 19485 E c.s.s.w.AppBackupPruneWorker: 		... 32 common frames omitted
```
