### ISSUE TITLE
StaleDataException: Attempted to access a cursor after it has been closed.

### ISSUE THREAD

**Issue by grote** [stevesoltys/backup#828]
```ruby
12-31 02:38:54.377 14319 14473 E AppBackupWorker: Error during 'beforeBackup': 
12-31 02:38:54.377 14319 14473 E AppBackupWorker: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at android.database.BulkCursorToCursorAdaptor.getExtras(BulkCursorToCursorAdaptor.java:165)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at android.database.CursorWrapper.getExtras(CursorWrapper.java:117)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt$getLoadedCursor$2.invokeSuspend(SafHelper.kt:199)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt$getLoadedCursor$2.invoke(Unknown Source:8)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt$getLoadedCursor$2.invoke(Unknown Source:4)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:89)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:151)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:46)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt.getLoadedCursor(SafHelper.kt:195)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt.getLoadedCursor$default(SafHelper.kt:194)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt.listFilesBlocking(SafHelper.kt:112)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at org.calyxos.seedvault.core.backends.saf.SafBackend.listFilesRecursive(SafBackend.kt:194)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at org.calyxos.seedvault.core.backends.saf.SafBackend.list(SafBackend.kt:124)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at com.stevesoltys.seedvault.repo.AppBackupManager.beforeBackup(AppBackupManager.kt:64)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at com.stevesoltys.seedvault.worker.AppBackupWorker.doBackup(AppBackupWorker.kt:156)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at com.stevesoltys.seedvault.worker.AppBackupWorker.doWork(AppBackupWorker.kt:134)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at com.stevesoltys.seedvault.worker.AppBackupWorker$doWork$1.invokeSuspend(Unknown Source:14)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
12-31 02:38:54.377 14319 14473 E AppBackupWorker: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by grote** [comment]
Same happens for file backup:

```ruby
12-31 02:37:23.064 14319 14473 E StorageBackup: Error during backup
12-31 02:37:23.064 14319 14473 E StorageBackup: android.database.StaleDataException: Attempted to access a cursor after it has been closed.
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at android.database.BulkCursorToCursorAdaptor.throwIfCursorIsClosed(BulkCursorToCursorAdaptor.java:63)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at android.database.BulkCursorToCursorAdaptor.getExtras(BulkCursorToCursorAdaptor.java:165)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at android.database.CursorWrapper.getExtras(CursorWrapper.java:117)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt$getLoadedCursor$2.invokeSuspend(SafHelper.kt:199)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt$getLoadedCursor$2.invoke(Unknown Source:8)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt$getLoadedCursor$2.invoke(Unknown Source:4)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturnIgnoreTimeout(Undispatched.kt:89)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at kotlinx.coroutines.TimeoutKt.setupTimeout(Timeout.kt:151)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at kotlinx.coroutines.TimeoutKt.withTimeout(Timeout.kt:46)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt.getLoadedCursor(SafHelper.kt:195)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt.getLoadedCursor$default(SafHelper.kt:194)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt.listFilesBlocking(SafHelper.kt:112)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt.findFileBlocking(SafHelper.kt:164)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.seedvault.core.backends.saf.SafHelperKt.getOrCreateDirectory(SafHelper.kt:85)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.seedvault.core.backends.saf.DocumentFileCache.getOrCreateFile$packages__apps__Seedvault__core__android_common__seedvault_lib_core(DocumentFileCache.kt:50)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.seedvault.core.backends.saf.SafBackend.save(SafBackend.kt:91)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.backup.storage.backup.ChunkWriter.writeChunkData(ChunkWriter.kt:78)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.backup.storage.backup.ChunkWriter.writeChunk(ChunkWriter.kt:57)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.backup.storage.backup.FileBackup.backupFile(FileBackup.kt:95)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.backup.storage.backup.FileBackup.backupFiles(FileBackup.kt:45)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.backup.storage.backup.Backup.backupFiles(Backup.kt:148)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.backup.storage.backup.Backup.runBackup(Backup.kt:127)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at org.calyxos.backup.storage.api.StorageBackup$runBackup$2.invokeSuspend(StorageBackup.kt:194)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
12-31 02:37:23.064 14319 14473 E StorageBackup: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by grote** [comment]
In both cases it fails on first SAF access, we try to get extras from the cursor right after receiving it and then it throws because the cursor was already closed which is shouldn't be unless our co-routine got cancelled right in this moment which is unlikely, but we could add some logging to be sure. Still, normally, we don't get cancelled here, so my best bet is on some SAF/flash-drive issue.

**Comment by t-m-w** [comment]
Not seeing this with https://github.com/seedvault-app/seedvault/pull/835 (https://github.com/seedvault-app/seedvault/commit/1597c9e3f68dbe0f088b967974fe559b1d037d05). Note however that I didn't check beforehand and am not sure how to reproduce it. What I've done is plug in a flash drive a few times and observed a backup happening automatically (I modded it for shorter frequencies, but that shouldn't be relevant), and then looked at logs.

**Comment by Lppsoeht** [comment]
Never succeeded restoring a backup, always this error shows up, I remember a similar error happening a few months ago if it's any help.

**Comment by grote** [comment]
@Lppsoeht is this with version 5.1 or 5.2? If so, please wait for 5.3 which fixes the issues. Also using a different backup location should fix it.
